config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", except: [:index , :new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    end
  resources :listings

  get '/tags/:tag', to: 'listings#index', as: :tag
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get '/dashboard', to: "listings#index", as: "index"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

   root 'static#index'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

 def self.create_with_omniauth(auth_hash)
   create! do |auth|
     auth.provider = auth_hash["provider"]
     auth.uid = auth_hash["uid"]
     auth.token = auth_hash["credentials"]["token"]
   end
 end

 def update_token(auth_hash)
   self.token = auth_hash["credentials"]["token"]
   self.save
 end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  #  attr_accessible :tag_list
  belongs_to :user
  #listing
  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :authentications, :dependent => :destroy
  has_many :listings



def self.create_with_auth_and_hash(authentication,auth_hash)
  create! do |u|
    u.first_name = auth_hash["info"]["first_name"]
    u.email = auth_hash["extra"]["raw_info"]["email"]
    u.encrypted_password = SecureRandom.urlsafe_base64
    u.remember_token = SecureRandom.urlsafe_base64
    u.authentications<<(authentication)
  end
end

def fb_token
  x = self.authentications.where(:provider => :facebook).first
  return x.token unless x.nil?
end

def password_optional?
  true
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

end

app/controllers/listings_controller.rb
# require 'byebug'

class ListingsController < ApplicationController


  def index
    if params[:tag]
      @listings = current_user.listings.tagged_with(params[:tag])
    else
      @listings = current_user.listings.all
    end
  end

  def show

    @listing = Listing.find(params[:id])
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.new(permit_params)
      if @listing.save
         redirect_to @listing

      else
        render 'new'
      end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(permit_params)
      redirect_to @listing
    else
      render 'edit'
    end
  end


  def destroy
  @listing = Listing.find(params[:id])
  @listing.destroy

    flash[:success] = "Listing deleted"
      redirect_to @listing


  end
end


private

def permit_params
    params.require(:listing).permit(:tag_list, :name, :desc, :country, :state, :city, :address, :property_type, :room_type, :no_of_guest, :price_per_night)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]

        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
        if authentication.user
          user = authentication.user
          authentication.update_token(auth_hash)
          @next = root_url
          @notice = "Signed in!"
        else
          user = User.create_with_auth_and_hash(authentication,auth_hash)
          @next = edit_user_path(user)
          @notice = "User created - confirm or edit details..."
        end
        sign_in(user)
        redirect_to @next, :notice => @notice
  end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
     def index
         @listings = Listing.all
     end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

    before_action :check_user, only: [:edit, :show]

    def edit
      @user = User.find(params[:id])
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])

      if @user.update(permit_params)
        redirect_to @user
      else
        render 'edit'
      end
    end




    private
    def user_from_params
      user_params = params[:user] || Hash.new

      email = user_params.delete(:email)
      password = user_params.delete(:password)
      first_name = user_params.delete(:first_name)
      last_name = user_params.delete(:last_name)
      gender = user_params.delete(:gender)
      birthday = [user_params.delete("birthday(1i)"),user_params.delete("birthday(2i)"),user_params.delete("birthday(3i)")].join(".")
      contact_number = user_params.delete(:contact_number)
      country = user_params.delete(:country)

      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.email = email
        user.password = password
        user.first_name = first_name
        user.last_name = last_name
        user.gender = gender
        user.birthday = birthday
        user.contact_number = contact_number
        user.country = country
      end
    end

    def permit_params
        params.require(:user).permit(:first_name, :last_name, :gender, "birthday(1i)","birthday(2i)","birthday(3i)", :contact_number, :country, :email, :password, :description)
    end

    def check_user
      @user = User.find(params[:id])
      unless @user && @user == current_user
        flash[:warning] = "Invalid Page!"
        redirect_to '/'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>

        <title>AirBnB</title>
        <link rel="shortcut icon" href="bnblogo.png"><link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>

    </head>

    <body>

        <nav class="navbar navbar-findcond ">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
      <% if signed_in? %>
                <%= link_to image_tag('bnblogo.png'), root_path(current_user), class:"navbar-brand"%>
      <%else%>
                <%=link_to image_tag('bnblogo.png'), root_path, class:"navbar-brand"%>
      <%end%>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <i class="fa fa-fw fa-bell-o"></i>
                                Notifications
                                <span class="badge">0</span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-fw fa-tag"></i>
                                        <span class="badge">Promotion</span>
                                        Last call for Promotion!
                                        <span class="badge">Listing</span>
                                        Enquiry: I was checking..</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-fw fa-thumbs-o-up"></i>
                                        <span class="badge">Booking</span>
                                        Booking Confirmed</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-fw fa-thumbs-o-up"></i>
                                        <span class="badge">Listing</span>
                                        Enquiry: Hi There!</a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-fw fa-thumbs-o-up"></i>
                                        <span class="badge">Game</span>
                                        sayfasında iletiniz beğenildi</a>
                                </li>
                            </ul>
                        </li>


                        <li class="active">
                            <a href="#">My Trips<span class="sr-only">(current)</span>
                            </a>
                        </li>

            <% if signed_in? %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.first_name %>
                                <span class="caret"></span>
                            </a>


                            <ul class="dropdown-menu" role="menu">

                                <li><%= link_to 'My Profile' , user_path(current_user) %></li>
                                <li class="divider"></li>
                                <li><%= link_to 'My Listings', listings_path %></li>
                                <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-right search-form" role="search">
                        <input type="text" class="form-control" placeholder="Search"/>
                    </form>
                <%else%>

                      <ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>

<ul id="login-dp" class="dropdown-menu">
  <li>
     <div class="row">
        <div class="col-md-12">
          Login via
          <div class="social-buttons">
            <a href="/auth/facebook" class="btn btn-tw"><i class="fa fa-twitter"></i> Facebook</a>
            <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
                          <p>or</p>
           <form class="form" role="form" method="post" action="/session" accept-charset="UTF-8" id="login-nav">
              <div class="form-group">
                 <label class="sr-only" for="exampleInputEmail2">Email address</label>
                 <input type="email" name='session[email]' class="form-control" id="exampleInputEmail2" placeholder="Email address" required >
              </div>
              <div class="form-group">
                 <label class="sr-only" for="exampleInputPassword2">Password</label>
                 <input type="password" name='session[password]'class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                       <div class="help-block text-right"><a href="">Forget the password ?</a></div>
              </div>

              <div class="form-group">

                <div class="submit-field"><input type="submit" name="commit" value="Sign in"></div>

              </div>
              <div class="checkbox">
                 <label>
                 <input type="checkbox"> keep me logged-in
                 </label>
              </div>
           </form>
        </div>
        <div class="bottom text-center">
          New here ? <a href="/sign_up"><b>Join Us</b></a>
        </div>
     </div>
  </li>
</ul>
  </li>
</ul>


<% end %>
              </div>

            </div>
        </nav>


        <% if !signed_in? %>

        <% end %>

        <div id="flash">
            <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
            <% end %>
        </div>

        <div id="container">
            <%= yield %>
        </div>

    </body>




<footer>
  <div class= "footer_box">
  <div class="container text-center">
    <hr />
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#">About us</a></li>
          <li><a href="#">Careers</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#">Travel Blog</a></li>
          <li><a href="#">Careers</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#">Help</a></li>
          <li><a href="#">Trust & Safety</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="#">Why Host</a></li>
          <li><a href="#">Hospitality</a></li>
        </ul>
      </div>
    </div>
  </div>
  <hr>
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-pills nav-justified">
                <li><a href="/">© 2016 AirBnB.</a></li>
                <li><a href="#">Terms of Service</a></li>
                <li><a href="#">Privacy</a></li>
            </ul>
        </div>
    </div>
</div>

<!-- Social media -->


<div class="container">
	<div class="social-media">

                                 <ul class="social">
                                  <li class="facebook"><a href="http://facebook.com/alterowo"><i class="fa fa-facebook fa-3x"></i></a></li>
                                  <li class="twitter"><a href="http://twitter.com/Kyokushinowa"><i class="fa fa-twitter fa-3x"></i></a></li>
                                  <li class="pinterest"><a href="http://www.pinterest.com/beatagibalska/"><i class="fa fa-pinterest-p fa-3x"></i></a></li>
                                  <li class="behance"><a href="https://www.behance.net/Kurnikowa"><i class="fa fa-behance fa-3x"></i></a></li>
                                </ul>
                          </div>
    </div>
    </div>

</div>
</div>
</footer>
</html>

app/views/listings/delete.html.erb
<h1>Listing#delete</h1>
<p>Find me in app/views/listing/delete.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listing#edit</h1>
<p>Find me in app/views/listing/edit.html.erb</p>



<%="Edit LISTINGS HERE"%>

<%= form_for @listing do |f| %>

<%= f.label :tag_list, "Tags (Seperated by Commas)" %>
<%= f.text_field :tag_list %><br>

<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :desc %>
<%= f.text_area :desc %><br>

<%= f.label :country %>
<%= f.country_select :country %><br>

<%= f.label :state %>
<%= f.text_field :state %><br>

<%= f.label :city %>
<%= f.text_field :city %><br>

<%= f.label :address %>
<%= f.text_field :address , size: "24x6" %><br>

<%= f.label :property_type %>
<%= f.select :property_type, options_for_select(
[
  ["Apartment", "Apartment"],
  ["House", "House"],
  ["Bed & Breakfast", "Bed & Breakfast"],
  ["Loft", "Loft"],
  ["Townhouse", "Townhouse"],
  ["Condominium", "Condominium"],
  ["Bungalow", "Bungalow"],
  ["Cabin", "Cabin"],
  ["Villa", "Villa"],
  ["Dorm", "Dorm"],
  ["Chalet", "Chalet"],
  ["Island", "Island"],
]
) %><br>

<%= f.label :room_type %>
<%= f.select :room_type, options_for_select(
[
  ["Entire Home/Apt", "Entire Home/Apt"],
  ["Private","Private"],
  ["Shared","Shared"]
]
)%><br>

<%= f.label :no_of_guest %>
<%= f.select :no_of_guest, options_for_select(
[
  ["1"],
  ["2"],
  ["3"],
  ["4"],
  ["5"],
  ["6"],
  ["7"],
  ["8"],
  ["9"],
  ["10 & above"]
]
)
%><br>

<%= f.label :price_per_night%>
<%= f.text_field :price_per_night %><br>

<%= f.submit "Edit listing"%>

<%end%>

app/views/listings/index.html.erb
<h1>All Your Listings</h1>

<%= link_to 'Create new Listing', new_listing_path %>
<br><br><br>
<% @listings.each do |x| %>
  <%= link_to x.name, listing_path(x) %><br>
  <%= x.desc %><br>
  Tag: <%=raw x.tag_list.map {|t| link_to t, tag_path(t)}.join(', ')%><br><br>
<% end %>

app/views/listings/new.html.erb
<%="CREATE NEW LISTINGS HERE"%>

<%= form_for @listing do |f| %>

<%= f.label :tag_list, "Tags (Seperated by Commas)" %>
<%= f.text_field :tag_list %><br>

<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :desc %>
<%= f.text_area :desc %><br>

<%= f.label :country %>
<%= f.country_select :country %><br>

<%= f.label :state %>
<%= f.text_field :state %><br>

<%= f.label :city %>
<%= f.text_field :city %><br>

<%= f.label :address %>
<%= f.text_field :address , size: "24x6" %><br>

<%= f.label :property_type %>
<%= f.select :property_type, options_for_select(
[
  ["Apartment", "Apartment"],
  ["House", "House"],
  ["Bed & Breakfast", "Bed & Breakfast"],
  ["Loft", "Loft"],
  ["Townhouse", "Townhouse"],
  ["Condominium", "Condominium"],
  ["Bungalow", "Bungalow"],
  ["Cabin", "Cabin"],
  ["Villa", "Villa"],
  ["Dorm", "Dorm"],
  ["Chalet", "Chalet"],
  ["Island", "Island"],
]
) %><br>

<%= f.label :room_type %>
<%= f.select :room_type, options_for_select(
[
  ["Entire Home/Apt", "Entire Home/Apt"],
  ["Private","Private"],
  ["Shared","Shared"]
]
)%><br>

<%= f.label :no_of_guest %>
<%= f.select :no_of_guest, options_for_select(
[
  ["1"],
  ["2"],
  ["3"],
  ["4"],
  ["5"],
  ["6"],
  ["7"],
  ["8"],
  ["9"],
  ["10 & above"]
]
)
%><br>

<%= f.label :price_per_night%>
<%= f.text_field :price_per_night %><br>

<%= f.submit "Start Listing"%>

<%end%>

app/views/listings/show.html.erb
<h1>Your listing</h1>


<%= @listing.name %><br>
<%= @listing.desc %><br>
Tag: <%=raw @listing.tag_list.map {|t| link_to t, tag_path(t)}.join(', ')%><br><br>

		<% if current_user.id == @listing.user_id %>
<%= link_to 'Edit Listing' , edit_listing_path(@listing) %>

<%= link_to 'Delete Listing' , @listing, method: :delete, data: {confirm:"Are you sure?"} %>
<%end%>

app/views/listings/update.html.erb
<h1>Listing#update</h1>
<p>Find me in app/views/listing/update.html.erb</p>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="first_name-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>

<div class="last_name-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>

<!-- <div class="gender-field">
  <%= form.label :gender %>
  <%= form.select :gender, options_for_select([["Male", "M"], ["Female", "F"], ["Others", "O"]]) %>
</div> -->

<div class="birthday-field">
  <%= form.label :birthday %>
  <%= form.date_select :birthday , start_year: Date.today.year-100, end_year: Date.today.year%>
</div>

<!-- <div class="contact_number-field">
  <%= form.label :contact_number %>
  <%= form.telephone_field :contact_number %>
</div> -->

<!-- <div class="description-field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div> -->

<!-- <div class="country-field">
  <%= form.label :country %>
  <%= form.country_select :country %>
</div> -->

app/views/users/dashboard.erb
<h1>Dashboard</h1>

app/views/users/edit.html.erb
<h3>This is where you edit your profile</h3>

<%= form_for @user do |form| %>

<div class="edit-form">
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>
<br>
<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
<br>
<div class="first_name-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
</div>
<br>
<div class="last_name-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
</div>
<br>
<div class="gender-field">
  <%= form.label :gender %>
  <%= form.select :gender, options_for_select([["Male", "M"], ["Female", "F"], ["Others", "O"]]) %>
</div>
<br>
<div class="birthday-field">
  <%= form.label :birthday %>
  <%= form.date_select :birthday , start_year: Date.today.year-100, end_year: Date.today.year%>
</div>
<br>
<div class="contact_number-field">
  <%= form.label :contact_number %>
  <%= form.telephone_field :contact_number %>
</div>
<br>
<div class="country-field">
  <%= form.label :country %>
  <%= form.country_select :country %>
</div>
<br>
<div class="description-field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>
<br>
<div class="edit-btn">
<%= form.submit "Update Profile"%>
</div>
<%end%>

</div>

app/views/users/new.html.erb
<!-- Begin container -->

  <!-- <%= form_for @user do |form| %> -->

<form method="post", action="/users">
  <div class='container'>
    <div class='container_inner'>
      <br>

      <fieldset>
        <div class='kickass_field'>
            <input maxlength='30' required='required' type='email' name='user[email]'>
          <lable>
            E-mail
            <span>Your Current E-mail</span>
          </lable>
        </div>


        <div class='kickass_field'>
            <input maxlength='30' required='required' type='password' name='user[password]'>
          <lable>
            Password
            <span>Minimum of 6 characters</span>
          </lable>
        </div>


        <div class='kickass_field'>
            <input maxlength='30' required='required' type='text' name='user[first_name]'>
          <lable>
            First Name
            <span>First Name</span>
          </lable>
        </div>
        <div class='kickass_field'>
            <input maxlength='30' required='required' type='text' name='user[last_name]'>
          <lable>
            Last Name
            <span>Last Name</span>
          </lable>
        </div>

        <div class="button">
          <input type='submit' value='Sign In'>
        </div>

        <%end%>
      </fieldset>
    </br>
</form>

app/views/users/show.html.erb
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">

<p class=" text-info">Member Since: <%=@user.created_at%> </p>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >


          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @user.first_name %> <%= @user.last_name %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>


                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Full Name:</td>
                        <td><%=@user.first_name%> <%=@user.last_name%></td>
                      </tr>
                      <tr>
                        <td>Current Email</td>
                        <td><%= @user.email %></td>
                      </tr>
                      <tr>
                        <td>Date of Birth</td>
                        <td><%= @user.birthday %></td>
                      </tr>

                         <tr>
                             <tr>
                        <td>Gender</td>
                        <td><%= @user.gender%></td>
                      </tr>
                        <tr>
                        <td>Nationality</td>
                        <td><%=@user.country%></td>
                      </tr>
                        <td>Phone Number</td>
                        <td> <%= @user.contact_number %>
                      </td>
                      <tr>
                        <td>About Me</td>
                        <td><%= @user.description %></td>
                      </tr>

                      </tr>

                    </tbody>
                  </table>

                  <%=link_to 'Edit Profile', edit_user_path(@user) , class:"btn btn-primary"%>
                  <%=link_to 'View My Listings', listings_path(@user) , class:"btn btn-primary"%>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>

          </div>
        </div>
      </div>
    </div>


































<!-- <h3>My Account</h3> -->
<!-- <p>Edit your profile on this page</p> -->

<!-- <h3>Full Name :</h3>
<%= @user.first_name %><%= @user.last_name %>

<h3> Contact Number </h3><%= @user.contact_number %>

<h3> Nationality </h3><%= @user.country %>

<h3> Password </h3><%= @user.password %>

<h3> Description </h3><%= @user.description %>
<br><br>
<%= link_to "Edit Profile", edit_user_path(@user)%> -->